os:
  - linux

dist: focal

language: c

compiler: gcc

env:
  - TEST="test.sh --job_control" DBG_FLAGS="-fsanitize=address -ggdb -O0 -coverage -DHIDE_PID -DHIDE_NOTIF"
  - TEST=norminette.sh

addons:
  apt:
    packages:
      - make
      - gcc
      - libncurses-dev
      - tcsh
      - coreutils
      - ruby
      - ruby-bundler
      - ruby-dev
      - bsdutils
      - automake
      - gettext
      - libtool-bin
      - bison
      - autopoint

install: 
  - test "$TEST" == "test.sh" && wget http://mirrors.kernel.org/ubuntu/pool/main/b/bash/bash_5.0-6ubuntu1_amd64.deb http://mirrors.kernel.org/ubuntu/pool/main/n/ncurses/libtinfo6_6.2-0ubuntu2_amd64.deb && sudo dpkg -i libtinfo*.deb && sudo dpkg -i bash*.deb || test "$TEST" != "test.sh" 
  - test "$TEST" == "test.sh" && wget https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/util-linux/2.36-3ubuntu1/util-linux_2.36.orig.tar.xz && tar -xf util-linux_2.36.orig.tar.xz && cd util-linux-2.36 && ./autogen.sh && ./configure && make -j3 scriptlive && mv scriptlive /tmp/ && export PATH="$PATH":/tmp/ && cd .. || test "$TEST" != "test.sh"
  - test "$TEST" == "test.sh" && make -j3 || test "$TEST" != "test.sh"

script:
  - tests/"$TEST"
  - gcov --version

after_success: test "$TEST" == "test.sh" && bash <(curl -s https://codecov.io/bash)
