os:
  - linux

dist: xenial

language: c

compiler: gcc

env:
  - TEST=test.sh DBG_FLAGS="-fsanitize=address -ggdb -O0 -coverage"
  - TEST=norminette.sh

addons:
  apt:
    packages:
      - make
      - gcc
      - libncurses-dev
      - tcsh
      - coreutils
      - ruby
      - ruby-bundler
      - ruby-dev

install: test "$TEST" == "test.sh" && make -j3 || true
script:
  - tests/"$TEST"
  - gcov --version
after_success: test "$TEST" == "test.sh" && bash <(curl -s https://codecov.io/bash)
