os:
  - linux

dist: xenial

language: c

compiler: clang

env:
  - DBG_FLAGS="-fsanitize=address -ggdb -O0 -coverage" ASAN_OPTIONS="detect_odr_violation=0"

addons:
  apt:
    packages:
      - make
      - clang
      - libncurses-dev
      - tcsh
      - ruby
      - ruby-bundler
      - ruby-dev

install: make -j3
script:
  - tests/test.sh
  - tests/norminette.sh
  - gcov --version
after_success: bash <(curl -s https://codecov.io/bash)
